//
//  BDInput_NameSpaceExtension.h
//  BDVRPreProcessLib
//
//  Created by  段弘 on 13-12-22.
//  Copyright (c) 2013年 百度. All rights reserved.
//

#ifdef  BD_USING_NAMESPACE_EXTENSION

#ifndef BD_PROJECT_NAMESPACE_EXTENSION
#define BD_PROJECT_NAMESPACE_EXTENSION BD_
#endif

#ifndef BD_SYMBOL_NAMESPACE_EXTENSION_PRIVATE
#define BD_SYMBOL_NAMESPACE_EXTENSION_PRIVATE(SYMBOL, EXTENSION) EXTENSION##SYMBOL
#endif

#ifndef BD_SYMBOL_NAMESPACE_EXTENSION_PUBLIC
#define BD_SYMBOL_NAMESPACE_EXTENSION_PUBLIC(SYMBOL, EXTENSION) BD_SYMBOL_NAMESPACE_EXTENSION_PRIVATE(SYMBOL, EXTENSION)
#endif

#ifndef BD_SYMBOL_WITH_NAMESPACE
#define BD_SYMBOL_WITH_NAMESPACE(SYMBOL) BD_SYMBOL_NAMESPACE_EXTENSION_PUBLIC(SYMBOL, BD_PROJECT_NAMESPACE_EXTENSION)
#endif

#define	BV32_BitPack				BD_SYMBOL_WITH_NAMESPACE(BV32_BitPack)
#define	BV32_BitUnPack				BD_SYMBOL_WITH_NAMESPACE(BV32_BitUnPack)
#define	coarsepitch 				BD_SYMBOL_WITH_NAMESPACE(coarsepitch)
#define	Reset_BV32_Decoder 			BD_SYMBOL_WITH_NAMESPACE(Reset_BV32_Decoder)
#define	BV32_Decode 				BD_SYMBOL_WITH_NAMESPACE(BV32_Decode)
#define	Reset_BV32_Encoder 			BD_SYMBOL_WITH_NAMESPACE(Reset_BV32_Encoder)
#define	BV32_Encode 				BD_SYMBOL_WITH_NAMESPACE(BV32_Encode)
#define	excdec_w_LT_synth 			BD_SYMBOL_WITH_NAMESPACE(excdec_w_LT_synth)
#define	excquan 				BD_SYMBOL_WITH_NAMESPACE(excquan)
#define	refinepitch 				BD_SYMBOL_WITH_NAMESPACE(refinepitch)
#define	bin2int_16 				BD_SYMBOL_WITH_NAMESPACE(bin2int_16)
#define	int2bin_16 				BD_SYMBOL_WITH_NAMESPACE(int2bin_16)
#define	bv32_fwrite_g192bitstrm 		BD_SYMBOL_WITH_NAMESPACE(bv32_fwrite_g192bitstrm)
#define	bv32_fread_g192bitstrm 			BD_SYMBOL_WITH_NAMESPACE(bv32_fread_g192bitstrm)
#define	gaindec 				BD_SYMBOL_WITH_NAMESPACE(gaindec)
#define	gainplc 				BD_SYMBOL_WITH_NAMESPACE(gainplc)
#define	gainquan 				BD_SYMBOL_WITH_NAMESPACE(gainquan)
#define	estlevel 				BD_SYMBOL_WITH_NAMESPACE(estlevel)
#define	lspdec 					BD_SYMBOL_WITH_NAMESPACE(lspdec)
#define	lspplc 					BD_SYMBOL_WITH_NAMESPACE(lspplc)
#define	lspquan 				BD_SYMBOL_WITH_NAMESPACE(lspquan)
#define	vqwmse 					BD_SYMBOL_WITH_NAMESPACE(vqwmse)
#define	vqwmse_stbl 				BD_SYMBOL_WITH_NAMESPACE(vqwmse_stbl)
#define	vqmse 					BD_SYMBOL_WITH_NAMESPACE(vqmse)
#define	BV32_PLC 				BD_SYMBOL_WITH_NAMESPACE(BV32_PLC)
#define	preprocess 				BD_SYMBOL_WITH_NAMESPACE(preprocess)
#define	pitchtapquan 				BD_SYMBOL_WITH_NAMESPACE(pitchtapquan)
#define	residual_energy 			BD_SYMBOL_WITH_NAMESPACE(residual_energy)
#define	FNevChebP 				BD_SYMBOL_WITH_NAMESPACE(FNevChebP)
#define	a2lsp 					BD_SYMBOL_WITH_NAMESPACE(a2lsp)
#define	FNevChebP 				BD_SYMBOL_WITH_NAMESPACE(FNevChebP)
#define	apfilter 				BD_SYMBOL_WITH_NAMESPACE(apfilter)
#define	apfilterQ1_Q0 				BD_SYMBOL_WITH_NAMESPACE(apfilterQ1_Q0)
#define	azfilter 				BD_SYMBOL_WITH_NAMESPACE(azfilter)
#define	azfilterQ0_Q1 				BD_SYMBOL_WITH_NAMESPACE(azfilterQ0_Q1)
#define	Autocorr 				BD_SYMBOL_WITH_NAMESPACE(Autocorr)
#define	Spectral_Smoothing 			BD_SYMBOL_WITH_NAMESPACE(Spectral_Smoothing)
#define	Levinson 				BD_SYMBOL_WITH_NAMESPACE(Levinson)
#define	get_pq_polynomial 			BD_SYMBOL_WITH_NAMESPACE(get_pq_polynomial)
#define	lsp2a 					BD_SYMBOL_WITH_NAMESPACE(lsp2a)
#define	get_pq_polynomials 			BD_SYMBOL_WITH_NAMESPACE(get_pq_polynomials)
#define	Pow2 					BD_SYMBOL_WITH_NAMESPACE(Pow2)
#define	Log2 					BD_SYMBOL_WITH_NAMESPACE(Log2)
#define	sqrts 					BD_SYMBOL_WITH_NAMESPACE(sqrts)
#define	sqrt_i 					BD_SYMBOL_WITH_NAMESPACE(sqrt_i)
#define	allocWord16 				BD_SYMBOL_WITH_NAMESPACE(allocWord16)
#define	allocEncoderState 			BD_SYMBOL_WITH_NAMESPACE(allocEncoderState)
#define	allocDecoderState 			BD_SYMBOL_WITH_NAMESPACE(allocDecoderState)
#define	allocBitStream 				BD_SYMBOL_WITH_NAMESPACE(allocBitStream)
#define	deallocWord16 				BD_SYMBOL_WITH_NAMESPACE(deallocWord16)
#define	deallocEncoderState 			BD_SYMBOL_WITH_NAMESPACE(deallocEncoderState)
#define	deallocDecoderState 			BD_SYMBOL_WITH_NAMESPACE(deallocDecoderState)
#define	deallocBitStream 			BD_SYMBOL_WITH_NAMESPACE(deallocBitStream)
#define	allocWord32 				BD_SYMBOL_WITH_NAMESPACE(allocWord32)
#define	deallocWord32 				BD_SYMBOL_WITH_NAMESPACE(deallocWord32)
#define	pp3dec 					BD_SYMBOL_WITH_NAMESPACE(pp3dec)
#define	stblz_lsp 				BD_SYMBOL_WITH_NAMESPACE(stblz_lsp)
#define	stblchck 				BD_SYMBOL_WITH_NAMESPACE(stblchck)
#define	W16copy 				BD_SYMBOL_WITH_NAMESPACE(W16copy)
#define	W16zero 				BD_SYMBOL_WITH_NAMESPACE(W16zero)
#define	W32copy 				BD_SYMBOL_WITH_NAMESPACE(W32copy)
#define	vqdec 					BD_SYMBOL_WITH_NAMESPACE(vqdec)
#define	L_Extract 				BD_SYMBOL_WITH_NAMESPACE(L_Extract)
#define	L_Comp 					BD_SYMBOL_WITH_NAMESPACE(L_Comp)
#define	Mpy_32 					BD_SYMBOL_WITH_NAMESPACE(Mpy_32)
#define	Mpy_32_16 				BD_SYMBOL_WITH_NAMESPACE(Mpy_32_16)
#define	Div_32 					BD_SYMBOL_WITH_NAMESPACE(Div_32)
#define	saturate 				BD_SYMBOL_WITH_NAMESPACE(saturate)
#define	add 					BD_SYMBOL_WITH_NAMESPACE(add)
#define	sub 					BD_SYMBOL_WITH_NAMESPACE(sub)
#define	abs_s 					BD_SYMBOL_WITH_NAMESPACE(abs_s)
#define	shl 					BD_SYMBOL_WITH_NAMESPACE(shl)
#define	mult 					BD_SYMBOL_WITH_NAMESPACE(mult)
#define	shr 					BD_SYMBOL_WITH_NAMESPACE(shr)
#define	L_mult 					BD_SYMBOL_WITH_NAMESPACE(L_mult)
#define	negate 					BD_SYMBOL_WITH_NAMESPACE(negate)
#define	extract_h 				BD_SYMBOL_WITH_NAMESPACE(extract_h)
#define	extract_l 				BD_SYMBOL_WITH_NAMESPACE(extract_l)
#define	round30To16 				BD_SYMBOL_WITH_NAMESPACE(round30To16)
#define	L_mac 					BD_SYMBOL_WITH_NAMESPACE(L_mac)
#define	L_msu 					BD_SYMBOL_WITH_NAMESPACE(L_msu)
#define	L_macNs 				BD_SYMBOL_WITH_NAMESPACE(L_macNs)
#define	L_msuNs 				BD_SYMBOL_WITH_NAMESPACE(L_msuNs)
#define	L_add 					BD_SYMBOL_WITH_NAMESPACE(L_add)
#define	L_sub 					BD_SYMBOL_WITH_NAMESPACE(L_sub)
#define	L_add_c 				BD_SYMBOL_WITH_NAMESPACE(L_add_c)
#define	L_sub_c 				BD_SYMBOL_WITH_NAMESPACE(L_sub_c)
#define	L_negate 				BD_SYMBOL_WITH_NAMESPACE(L_negate)
#define	mult_r 					BD_SYMBOL_WITH_NAMESPACE(mult_r)
#define	L_shl 					BD_SYMBOL_WITH_NAMESPACE(L_shl)
#define	L_shr 					BD_SYMBOL_WITH_NAMESPACE(L_shr)
#define	shr_r 					BD_SYMBOL_WITH_NAMESPACE(shr_r)
#define	mac_r 					BD_SYMBOL_WITH_NAMESPACE(mac_r)
#define	msu_r 					BD_SYMBOL_WITH_NAMESPACE(msu_r)
#define	L_deposit_h 				BD_SYMBOL_WITH_NAMESPACE(L_deposit_h)
#define	L_deposit_l 				BD_SYMBOL_WITH_NAMESPACE(L_deposit_l)
#define	L_shr_r 				BD_SYMBOL_WITH_NAMESPACE(L_shr_r)
#define	L_abs 					BD_SYMBOL_WITH_NAMESPACE(L_abs)
#define	L_sat 					BD_SYMBOL_WITH_NAMESPACE(L_sat)
#define	norm_s 					BD_SYMBOL_WITH_NAMESPACE(norm_s)
#define	div_s 					BD_SYMBOL_WITH_NAMESPACE(div_s)
//---------------------------------------------------------------------
#define a_pre					BD_SYMBOL_WITH_NAMESPACE(a_pre)
#define acosslope				BD_SYMBOL_WITH_NAMESPACE(acosslope)
#define adf_h					BD_SYMBOL_WITH_NAMESPACE(adf_h)
#define adf_l					BD_SYMBOL_WITH_NAMESPACE(adf_l)
#define b_pre					BD_SYMBOL_WITH_NAMESPACE(b_pre)
#define bdf					BD_SYMBOL_WITH_NAMESPACE(bdf)
#define bfi					BD_SYMBOL_WITH_NAMESPACE(bfi)
#define bit_table				BD_SYMBOL_WITH_NAMESPACE(bit_table)
#define bwel					BD_SYMBOL_WITH_NAMESPACE(bwel)
#define Carry					BD_SYMBOL_WITH_NAMESPACE(Carry)
#define cccb					BD_SYMBOL_WITH_NAMESPACE(cccb)
#define costable				BD_SYMBOL_WITH_NAMESPACE(costable)
#define currCounter				BD_SYMBOL_WITH_NAMESPACE(currCounter)
#define grid					BD_SYMBOL_WITH_NAMESPACE(grid)
#define hpfa					BD_SYMBOL_WITH_NAMESPACE(hpfa)
#define hpfb					BD_SYMBOL_WITH_NAMESPACE(hpfb)
#define idxord					BD_SYMBOL_WITH_NAMESPACE(idxord)
#define invk					BD_SYMBOL_WITH_NAMESPACE(invk)
#define lgclimit				BD_SYMBOL_WITH_NAMESPACE(lgclimit)
#define lgmean					BD_SYMBOL_WITH_NAMESPACE(lgmean)
#define lgp					BD_SYMBOL_WITH_NAMESPACE(lgp)
#define lgpecb					BD_SYMBOL_WITH_NAMESPACE(lgpecb)
#define lgpecb_nh				BD_SYMBOL_WITH_NAMESPACE(lgpecb_nh)
#define lspecb1					BD_SYMBOL_WITH_NAMESPACE(lspecb1)
#define lspecb21				BD_SYMBOL_WITH_NAMESPACE(lspecb21)
#define lspecb22				BD_SYMBOL_WITH_NAMESPACE(lspecb22)
#define lspmean					BD_SYMBOL_WITH_NAMESPACE(lspmean)
#define lspp					BD_SYMBOL_WITH_NAMESPACE(lspp)
#define MPTH					BD_SYMBOL_WITH_NAMESPACE(MPTH)
#define Overflow				BD_SYMBOL_WITH_NAMESPACE(Overflow)
#define pp9cb					BD_SYMBOL_WITH_NAMESPACE(pp9cb)
#define sstwinl_h				BD_SYMBOL_WITH_NAMESPACE(sstwinl_h)
#define sstwinl_l				BD_SYMBOL_WITH_NAMESPACE(sstwinl_l)
#define STWAL					BD_SYMBOL_WITH_NAMESPACE(STWAL)
#define tablog					BD_SYMBOL_WITH_NAMESPACE(tablog)
#define tabpow					BD_SYMBOL_WITH_NAMESPACE(tabpow)
#define tabsqrt					BD_SYMBOL_WITH_NAMESPACE(tabsqrt)
#define winl					BD_SYMBOL_WITH_NAMESPACE(winl)
#define x					BD_SYMBOL_WITH_NAMESPACE(x)
#define x2					BD_SYMBOL_WITH_NAMESPACE(x2)
#define CAudioBitmap        BD_SYMBOL_WITH_NAMESPACE(CAudioBitmap)
#define isFirst             BD_SYMBOL_WITH_NAMESPACE(isFirst)
#define nVAD                BD_SYMBOL_WITH_NAMESPACE(nVAD)
#define nCompress           BD_SYMBOL_WITH_NAMESPACE(nCompress)
#define CFft                BD_SYMBOL_WITH_NAMESPACE(CFft)
#define nSampleRate         BD_SYMBOL_WITH_NAMESPACE(nSampleRate)
#define my_lower_bound      BD_SYMBOL_WITH_NAMESPACE(my_lower_bound)
#define isNull              BD_SYMBOL_WITH_NAMESPACE(isNull)

//-------------------------------feedback--------------------------------
#define		nSleep_Timeout_Init			BD_SYMBOL_WITH_NAMESPACE(nSleep_Timeout_Init)
#define		nSleep_Timeout			BD_SYMBOL_WITH_NAMESPACE(nSleep_Timeout)
#define		nSpeech_Mode_Init			BD_SYMBOL_WITH_NAMESPACE(nSpeech_Mode_Init)
#define		nSpeech_Mode			BD_SYMBOL_WITH_NAMESPACE(nSpeech_Mode)
#define		nCurState			BD_SYMBOL_WITH_NAMESPACE(nCurState)
#define		nFs			BD_SYMBOL_WITH_NAMESPACE(mfeSetLogLevel)
#define		nCodeFormat			BD_SYMBOL_WITH_NAMESPACE(nCodeFormat)
#define		lSample			BD_SYMBOL_WITH_NAMESPACE(lSample)
#define		lSampleStart			BD_SYMBOL_WITH_NAMESPACE(lSampleStart)
#define		lSampleEnd			BD_SYMBOL_WITH_NAMESPACE(lSampleEnd)
#define		nStartFrame			BD_SYMBOL_WITH_NAMESPACE(nStartFrame)
#define		nEndFrame			BD_SYMBOL_WITH_NAMESPACE(nEndFrame)
#define		nSpeechEncLength			BD_SYMBOL_WITH_NAMESPACE(nSpeechEncLength)
#define		MyMutex			BD_SYMBOL_WITH_NAMESPACE(MyMutex)
#define		g_pData			BD_SYMBOL_WITH_NAMESPACE(g_pData)
#define		g_pBVData			BD_SYMBOL_WITH_NAMESPACE(g_pBVData)
#define		lBVStartLoc			BD_SYMBOL_WITH_NAMESPACE(lBVStartLoc)
#define		lBVCurLoc			BD_SYMBOL_WITH_NAMESPACE(lBVCurLoc)
#define		frsz			BD_SYMBOL_WITH_NAMESPACE(frsz)
#define		sizebitstream			BD_SYMBOL_WITH_NAMESPACE(sizebitstream)
#define		sizestate			BD_SYMBOL_WITH_NAMESPACE(sizestate)
#define		state			BD_SYMBOL_WITH_NAMESPACE(state)
#define		bs			BD_SYMBOL_WITH_NAMESPACE(bs)
#define		frame			BD_SYMBOL_WITH_NAMESPACE(frame)
#define		PackedStream			BD_SYMBOL_WITH_NAMESPACE(PackedStream)
#define		iLogLevel			BD_SYMBOL_WITH_NAMESPACE(iLogLevel)
#define		nFrameLength			BD_SYMBOL_WITH_NAMESPACE(nFrameLength)
#define		nFrameShift			BD_SYMBOL_WITH_NAMESPACE(nFrameShift)
#define		MyCond			BD_SYMBOL_WITH_NAMESPACE(MyCond)
#define		ts			BD_SYMBOL_WITH_NAMESPACE(ts)
#define		norm_l			BD_SYMBOL_WITH_NAMESPACE(norm_l)
#define		L_mls			BD_SYMBOL_WITH_NAMESPACE(L_mls)
#define		div_l			BD_SYMBOL_WITH_NAMESPACE(div_l)
#define		i_mult			BD_SYMBOL_WITH_NAMESPACE(i_mult)
#define		L_mult0			BD_SYMBOL_WITH_NAMESPACE(L_mult0)
#define		L_mac0			BD_SYMBOL_WITH_NAMESPACE(L_mac0)
#define		L_msu0			BD_SYMBOL_WITH_NAMESPACE(L_msu0)

//My Functions and Global Variables
#define		FFT				BD_SYMBOL_WITH_NAMESPACE(FFT)
#define		Sort_QuickSort			BD_SYMBOL_WITH_NAMESPACE(Sort_QuickSort)
#define		OneQuickSort			BD_SYMBOL_WITH_NAMESPACE(OneQuickSort)
#define		mfeInit				BD_SYMBOL_WITH_NAMESPACE(mfeInit)
#define		mfePutCvn			BD_SYMBOL_WITH_NAMESPACE(mfePutCvn)
#define		mfeExit				BD_SYMBOL_WITH_NAMESPACE(mfeExit)
#define		mfeOpen				BD_SYMBOL_WITH_NAMESPACE(mfeOpen)
#define		mfeClose			BD_SYMBOL_WITH_NAMESPACE(mfeClose)
#define		mfeStart			BD_SYMBOL_WITH_NAMESPACE(mfeStart)
#define		mfeStop				BD_SYMBOL_WITH_NAMESPACE(mfeStop)
#define		mfeSendData			BD_SYMBOL_WITH_NAMESPACE(mfeSendData)
#define		mfeGetCallbackData		BD_SYMBOL_WITH_NAMESPACE(mfeGetCallbackData)
#define		mfeDetect			BD_SYMBOL_WITH_NAMESPACE(mfeDetect)
#define		mfeSetParam			BD_SYMBOL_WITH_NAMESPACE(mfeSetParam)
#define		mfeGetParam			BD_SYMBOL_WITH_NAMESPACE(mfeGetParam)
#define		mfeEnableNoiseDetection		BD_SYMBOL_WITH_NAMESPACE(mfeEnableNoiseDetection)
#define		mfeSetLogLevel			BD_SYMBOL_WITH_NAMESPACE(mfeSetLogLevel)

//amr
#define     serial              BD_SYMBOL_WITH_NAMESPACE(serial)
#define     signalwave          BD_SYMBOL_WITH_NAMESPACE(signalwave)
#define     coding_mode         BD_SYMBOL_WITH_NAMESPACE(coding_mode)
#define     st                  BD_SYMBOL_WITH_NAMESPACE(st)
#define     AMR_encode          BD_SYMBOL_WITH_NAMESPACE(AMR_encode)

// carlife drc
#define     nCarlife            BD_SYMBOL_WITH_NAMESPACE(nCarlife)
#define     drc_handle          BD_SYMBOL_WITH_NAMESPACE(drc_handle)
#define     drc_create          BD_SYMBOL_WITH_NAMESPACE(drc_create)
#define     drc_destroy         BD_SYMBOL_WITH_NAMESPACE(drc_destroy)
#define     drc_init            BD_SYMBOL_WITH_NAMESPACE(drc_init)
#define     drc_reset           BD_SYMBOL_WITH_NAMESPACE(drc_reset)
#define     drc_process         BD_SYMBOL_WITH_NAMESPACE(drc_process)
#define     clipping_detect     BD_SYMBOL_WITH_NAMESPACE(clipping_detect)
#define     SectCalcForm1       BD_SYMBOL_WITH_NAMESPACE(SectCalcForm1)
#define     iir_init            BD_SYMBOL_WITH_NAMESPACE(iir_init)
#define     iir_free            BD_SYMBOL_WITH_NAMESPACE(iir_free)
#define     iir_proc            BD_SYMBOL_WITH_NAMESPACE(iir_proc)
#define     iir_reset           BD_SYMBOL_WITH_NAMESPACE(iir_reset)
#define     NoiseLevel_Init_RP  BD_SYMBOL_WITH_NAMESPACE(NoiseLevel_Init_RP)
#define     NoiseLevel_RP       BD_SYMBOL_WITH_NAMESPACE(NoiseLevel_RP)


/*
#define		MSR_EVENT_START			BD_SYMBOL_WITH_NAMESPACE(MSR_EVENT_START)
#define		MSR_ERROR			BD_SYMBOL_WITH_NAMESPACE(MSR_ERROR)
#define		MSR_STATE			BD_SYMBOL_WITH_NAMESPACE(MSR_STATE)
#define		Enc_format			BD_SYMBOL_WITH_NAMESPACE(Enc_format)
#define		MSR_MessageCallBack		BD_SYMBOL_WITH_NAMESPACE(MSR_MessageCallBack)
#define		MSR_DataCallBack		BD_SYMBOL_WITH_NAMESPACE(MSR_DataCallBack)
#define		MSR_PutCvn			BD_SYMBOL_WITH_NAMESPACE(MSR_PutCvn)
#define		MSR_Init			BD_SYMBOL_WITH_NAMESPACE(MSR_Init)
#define		MSR_Exit			BD_SYMBOL_WITH_NAMESPACE(MSR_Exit)
#define		MSR_Open			BD_SYMBOL_WITH_NAMESPACE(MSR_Open)
#define		MSR_Close			BD_SYMBOL_WITH_NAMESPACE(MSR_Close)
#define		MSR_Start			BD_SYMBOL_WITH_NAMESPACE(MSR_Start)
#define		MSR_Stop			BD_SYMBOL_WITH_NAMESPACE(MSR_Stop)
#define		MSR_SendData			BD_SYMBOL_WITH_NAMESPACE(MSR_SendData)
#define		MSR_State			BD_SYMBOL_WITH_NAMESPACE(MSR_State)
#define		MSR_Detect			BD_SYMBOL_WITH_NAMESPACE(MSR_Detect)
#define		MSR_SetCodingFormat		BD_SYMBOL_WITH_NAMESPACE(MSR_SetCodingFormat)
#define		MSR_GetCodingFormat		BD_SYMBOL_WITH_NAMESPACE(MSR_GetCodingFormat)
#define		MSR_SetCallbackDatLen		BD_SYMBOL_WITH_NAMESPACE(MSR_SetCallbackDatLen)
#define		MSR_GetParam			BD_SYMBOL_WITH_NAMESPACE(MSR_GetParam)
#define		MSR_SetParam			BD_SYMBOL_WITH_NAMESPACE(MSR_SetParam)
#define		MSR_EnableNoiseDetection	BD_SYMBOL_WITH_NAMESPACE(MSR_EnableNoiseDetection)
*/

#endif
